Added detele functionality
Monfernape/shoes-rack pull request #196
Opened 2024-11-15 11:37 UTC by ghulamhafeez

## Implementations

- Added delete functionality
- Created delete server action

### Resources

https://github.com/user-attachments/assets/6e2d0b39-865f-47ed-9731-92a92734d296

2024-11-15 16:01 UTC, nadirhussain786 requested changes

2024-11-15 16:01 UTC, nadirhussain786 commented on src/app/attendance/components/AttendanceActionRender.tsx
>      router.push(`/attendance/edit/${id}`);
@ghulamhafeez use route enum

2024-11-18 09:21 UTC, Mubashar1009 approved these changes

2024-11-18 09:23 UTC, nadirhussain786 approved these changes

2024-11-18 09:23 UTC, merged