Added consistency in font sizing
Monfernape/shoes-rack pull request #208
Opened 2024-11-18 14:00 UTC by Mubashar1009

## Change Request

Font Sizes of the text  are different in different sections  in the project, add consistency in the font sizing so UI should be looking  good 

### Implementation

* Changed font size of the inputs according to the side bar items's text font size
* Changed font size of the date picker, labels , form labels according to the sidebar  items's text  font size
* Changed font size of  Tables List heading according to the sidebar  section heading and breadcrumbs section text

### Resources
<img width="1665" alt="image" src="https://github.com/user-attachments/assets/5a0fca50-39df-429e-aafb-f11b1eefee94">
<img width="1665" alt="image" src="https://github.com/user-attachments/assets/1f979441-6343-4ddc-bfa3-a2fb116e39db">

2024-11-18 19:04 UTC, Monfernape approved these changes

2024-11-25 08:29 UTC, muhammad-bilal-ali-khokhar approved these changes

2024-11-25 14:22 UTC, nadirhussain786 requested changes

2024-11-25 14:22 UTC, nadirhussain786 commented on src/app/members/components/MemberList.tsx
> +                  className="bg-gray-300 text-gray-700 text-left px-4 py-2 font-semibold text-sm"
@Mubashar1009  font size should be `xs`

2024-11-25 14:22 UTC, nadirhussain786 commented on src/common/FormTitle/FormTitle.tsx
> +    <h1 className="text-base font-semibold text-gray-800 my-4">{title}</h1>
@Mubashar1009 for font size should be `sm`.

2024-11-25 14:22 UTC, nadirhussain786 commented on src/components/ui/label.tsx
> +  "text-sm font-semibold leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
@Mubashar1009 font should be `font-medium`.

2024-11-25 14:22 UTC, nadirhussain786 commented on src/components/ui/form.tsx
> +      className={cn("text-sm font-semibold", className)}
@Mubashar1009 font size should be `xs` for label

2024-11-25 14:22 UTC, nadirhussain786 commented on src/components/ui/button.tsx
> +  "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-semibold transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:
@Mubashar1009 font weight should be remain `font-medium`

2024-11-27 13:15 UTC, nadirhussain786 approved these changes

2024-11-27 13:18 UTC, merged